# Generated by Django 5.0.6 on 2024-07-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_problem_aimodel_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.problem'),
        ),
    ]
