# Generated by Django 5.0.6 on 2024-07-06 17:46

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_type_alter_aimodel_problem_aimodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=backend.models.ai_model_upload_to),
        ),
    ]
