# Generated by Django 5.0.6 on 2024-07-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_aimodel_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.FloatField()),
                ('m2', models.FloatField()),
                ('m3', models.FloatField()),
                ('m4', models.FloatField()),
                ('m5', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.aimodel')),
            ],
        ),
    ]
