# Generated by Django 5.0.6 on 2024-07-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_modelevaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelevaluation',
            old_name='m1',
            new_name='mae',
        ),
        migrations.RenameField(
            model_name='modelevaluation',
            old_name='m2',
            new_name='mse',
        ),
        migrations.RemoveField(
            model_name='modelevaluation',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='modelevaluation',
            name='m4',
        ),
        migrations.RemoveField(
            model_name='modelevaluation',
            name='m5',
        ),
    ]
