# Generated by Django 5.0.6 on 2024-07-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_m1_modelevaluation_mae_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelevaluation',
            name='mae',
        ),
        migrations.RemoveField(
            model_name='modelevaluation',
            name='mse',
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='feesMae',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='feesMse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='highMae',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='highMse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='lowMae',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='modelevaluation',
            name='lowMse',
            field=models.FloatField(default=0.0),
        ),
    ]
